// frontend/src/components/map-wrapper/index.tsx
import React from 'react';
import { Station } from '../../types/station';
import LeafletMap from '../map';
import { getStationsById } from '../../services/StationService';

interface Location {
  x: number;
  y: number;
  name: string;
  id: number;
  color: string;
}

function MapWrapper(props: { stationIds: string[] }) {
  const [stations, setStations] = React.useState([] as Location[]);

  React.useEffect(() => {
    if (props.stationIds?.length) {
      getStationsById(props.stationIds).then((data: Station[]) => {
        const s = data.map((st, i) => {
          return {
            x: st.x_coordinate,
            y: st.y_coordinate,
            name: st.nimi,
            id: st.fid,
            color: st.id.toString() === props.stationIds[0] ? 'green' : 'red',
          };
        });
        setStations(s);
      });
    }
  }, [props.stationIds]);

  return (
    <LeafletMap
      locations={stations}
      onClick={() => ''}
      enableMarkerAdd={false}
    />
  );
}

export default MapWrapper;

// frontend-vue/src/components/MapWrapper.vue
<script setup lang="ts">
import { getStationsById } from "@/services/stationsService";
import type { Location, Station } from "@/types/station";
import { ref } from "vue";
import MapItemVue from "./MapItem.vue";
const props = defineProps<{
  stationIds: string[];
}>();

const stations = ref([] as Location[]);
if (props.stationIds?.length) {
  getStationsById(props.stationIds).then((data: Station[]) => {
    const s = data.map((st) => {
      return {
        lng: st.x_coordinate,
        lat: st.y_coordinate,
        name: st.nimi,
        id: st.fid,
        color: st.id.toString() === props.stationIds[0] ? "green" : "red",
      };
    });
    stations.value = s;
  });
}
</script>

<template>
  <MapItemVue :locations="stations"></MapItemVue>
</template>
