// frontend/src/components/searchbar/searchbar.tsx
import React from 'react';
import { Station } from '../../types/station';

interface SearchbarProps {
  searchStringChange: { (value: string): void };
  searchString: string;
  stations: Station[];
}

const Searchbar = (props: SearchbarProps) => {
  const [searchString, setsearchString] = React.useState(props.searchString);
  const [results, setResults] = React.useState([] as JSX.Element[]);

  React.useEffect( () => { 
    const filterFn = (s: Station) => {
      return searchString !== '' && [s.name, s.nimi, s.namn].some(n => n.includes(searchString) && n.toLowerCase() !== searchString.toLowerCase());
    }

    const getData = setTimeout(() => {
      setResults(props.stations.filter(s => filterFn(s)).map(s => (
        <span data-testid="search-item" key={s.id} onClick={(e) => {setsearchString(s.nimi); props.searchStringChange(s.nimi)}}>{s.name}</span>
      )))
    }, 500)
    return () => clearTimeout(getData)

  }, [searchString, props])

  return (
    <div data-testid="searchbar-parent" className="flex relative justify-center searchbar-parent pl-3">
      <div id="myDropdown" className="dropdown-content show">
        <input type="text" value={searchString} placeholder="Search.." id="myInput" onChange={(e) => {setsearchString(e.target.value); props.searchStringChange(e.target.value)}} />
        { results }
      </div>
    </div>
  );
};

export default Searchbar;

// frontend-vue/src/components/Searchbar.vue
<script setup lang="ts">
import { useStationStore } from '@/stores/stations';
import { reactive } from 'vue';
const stationStore = reactive(useStationStore());
const p = stationStore.getPagination;
let searchString = '';

const props = defineProps<{ 
  name: string;
  searchStringChange: any;
  setActive: any;
}>()
</script>

<template>
    <div
      class="flex relative searchbar-parent"
    >
      <div id="myDropdown" class="dropdown">
        <input
          type="text"
          v-model="searchString"
          placeholder="Search.."
          :id="props.name"
          class="searchbar"
          @keyup="(e: any) => {
            stationStore.changePagination({stationName: e.target.value});
            props.searchStringChange(e.target.value);
          }"
        />
        <div class="dropdown-content show">
          <span
            v-if="stationStore.filteredStations.length > 1 && searchString"
            v-for="s of stationStore.filteredStations"
            key={s.id}
            @click="(e: any) => {
              stationStore.changePagination({stationName: s.nimi});
              props.searchStringChange(s.nimi);
              searchString = s.nimi;
              props.setActive(props.name || '', s.id);
            }"
          >
            {{s.nimi}}
          </span>
        </div>
      </div>
    </div>
</template>
