// frontend/src/components/table-header/index.tsx
import classNames from 'classnames';

interface TableHeaderProps {
  clickFn: { (): void };
  label: string;
  ordering: 'DESC' | 'ASC';
  active: boolean;
  className: string[];
}

const TableHeader = (props: TableHeaderProps) => {
  const { clickFn, label, ordering, active, className } = props;
  return (
    <p
      className={classNames('flex', 'items-center', className)}
      onClick={clickFn}
    >
      {` ${label} `}
      {active && <i className={classNames('ml-2', 'ordering', ordering)}></i>}
    </p>
  );
};

export default TableHeader;

// frontend-vue/src/components/TableHeader.vue
<script setup lang="ts">
import classNames from 'classnames';
const props = defineProps<{ 
  clickFn: any;
  label: string;
  ordering: 'DESC' | 'ASC';
  active: boolean;
  className: string[];
}>()

</script>
<template>
  <p
    :class="classNames('flex', 'items-center', props.className)"
    @click="clickFn"
  >
    {{ props.label }}
    <i v-if="active" :class="classNames('ml-2', 'ordering', props.ordering)"></i>
  </p>
</template>
